config:
  backup: true
  banner: true
  create: true
  dotpath: ~/git/desktop/dotfiles01/dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  minversion: 1.15.0
dotfiles:
  dotdrop:
    src: dotdrop
    dst: ~/.config/dotdrop
    link: absolute
  alacritty:
    src: alacritty
    dst: ~/.config/alacritty
    link: absolute
  alacritty_msi:
    src: alacritty-msi
    dst: ~/.config/alacritty
    link: absolute
  nvim:
    src: nvim
    dst: ~/.config/nvim
    link: absolute
profiles:
  Default:
    dotfiles:
    - dotdrop
    - nvim
  msi:
    dotfiles:
    - alacritty_msi
  display4k:
    dotfiles:
    - alacritty
  rdv-msi-ubuntu2024:
    include:
    - Default
    - msi
  J7VZST3:
    include:
    - Default
    - display4k
