config:
  backup: true
  banner: true
  create: true
  dotpath: ~/git/desktop/dotfiles01/dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  minversion: 1.15.0

variables:
  font_size: '12.0'
dotfiles:
  dotdrop:
    src: dotdrop
    dst: ~/.config/dotdrop
    link: absolute
  alacritty:
    src: alacritty-template
    dst: ~/.config/alacritty
    link: absolute
  atuin:
    src: atuin
    dst: ~/.config/atuin
    link: absolute
  nvim:
    src: nvim
    dst: ~/.config/nvim
    link: absolute
  copyq:
    src: copyq
    dst: ~/.config/copyq
    link: link_children
profiles:
  Default:
    dotfiles:
    - dotdrop
    - nvim
    - atuin
  msi:
    dotfiles:
    - alacritty
  display4k:
    dotfiles:
    - alacritty
    - copyq
  msi:
    variables:
      font_size: '15.0'
  display4k:
    variables:
      font_size: '12.0'
  rdv-msi-ubuntu2024:
    include:
    - Default
    - msi
  J7VZST3:
    include:
    - Default
    - display4k
